// Auto-generated by scripts/exportAbis.js
// Re-run with: node scripts/exportAbis.js

const ADDRESSES = {
	"31337": {
		"GOLDToken": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
		"PlayerNFT": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
		"Leaderboard": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
		"BrickBreaker": "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
		"ConnectFour": "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
		"MemoryMatch": "0x0165878A594ca255338adfa4d48449f69242Eb8F",
		"Snake": "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
		"WordGuess": "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6"
	},
	"80002": {}
};

// Returns the correct address set for the connected network
export function getAddresses(chainId) {
	const addrs = ADDRESSES[chainId];
	if (addrs && Object.keys(addrs).length > 0) return addrs;
	throw new Error(`No deployment found for chain ID ${chainId}`);
}
