// Reads Hardhat artifact files and writes all ABI arrays into a single frontend/src/contracts/abis.js file. 
// Run this once after any contract changes:  node scripts/exportAbis.js

// Generates two files:
//      frontend/src/contracts/abis.js      --> all contract ABI arrays
//      frontend/src/contracts/addresses.js --> deployed addresses per network

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// __dirname is not available in ES modules, so we derive it from import.meta.url
const __dirname = path.dirname(fileURLToPath(import.meta.url));

/* ---------------------------------------- ABIs ---------------------------------------- */
// The contracts the frontend needs to interact with
const contracts = [
    "GOLDToken",
    "PlayerNFT",
    "Leaderboard",
    "WordGuess",
    "Snake",
    "BrickBreaker",
    "MemoryMatch",
    "ConnectFour",
];

const abis = {};

for (const name of contracts) {
    const artifactPath = path.join(
        __dirname,
        `../artifacts/contracts/${name}.sol/${name}.json`
    );
    const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
    abis[name] = artifact.abi;
    console.log(`✓ ${name}`);
}

const abisOutput =
    `// Auto-generated by scripts/exportAbis.js\n` +
    `// Re-run with: node scripts/exportAbis.js\n` +
    `const ABIS = ${JSON.stringify(abis, null, 2)};\n` +
    `export default ABIS;\n`;

const abisPath = path.join(__dirname, "../frontend/src/contracts/abis.js");
fs.mkdirSync(path.dirname(abisPath), { recursive: true });
fs.writeFileSync(abisPath, abisOutput);
console.log("\nDone -> frontend/src/contracts/abis.js");

/* ---------------------------------------- Addresses ---------------------------------------- */
// Map chain ID to the folder name Hardhat Ignition creates
const networks = {
    31337: "chain-31337",  // local Hardhat node
    80002: "chain-80002",  // Polygon Amoy testnet
};

// Map Ignition's generated keys to clean contract names
const keyMap = {
    "GOLDToken#GOLDToken": "GOLDToken",
    "PlayerNFT#PlayerNFT": "PlayerNFT",
    "Deploy#Leaderboard":  "Leaderboard",
    "Deploy#BrickBreaker": "BrickBreaker",
    "Deploy#ConnectFour":  "ConnectFour",
    "Deploy#MemoryMatch":  "MemoryMatch",
    "Deploy#Snake":        "Snake",
    "Deploy#WordGuess":    "WordGuess",
};

const addresses = {};

for (const [chainId, folder] of Object.entries(networks)) {
    const deployedPath = path.join(__dirname,
        `../ignition/deployments/${folder}/deployed_addresses.json`);

    if (!fs.existsSync(deployedPath)) {
        console.log(`No deployment found for chain ${chainId}, skipping.`);
        addresses[chainId] = {};
        continue;
    }

    const raw = JSON.parse(fs.readFileSync(deployedPath, "utf8"));

    // Convert Ignition keys like "Deploy#Snake" to clean names like "Snake"
    const cleaned = {};
    for (const [key, address] of Object.entries(raw)) {
        const name = keyMap[key];
        if (name) cleaned[name] = address;
    }

    addresses[chainId] = cleaned;
    console.log(`✓ Addresses: chain ${chainId}`);
}

const addressesOutput =
    `// Auto-generated by scripts/exportAbis.js\n` +
    `// Re-run with: node scripts/exportAbis.js\n\n` +
    `const ADDRESSES = ${JSON.stringify(addresses, null, "\t")};\n\n` +
    `// Returns the correct address set for the connected network\n` +
    `export function getAddresses(chainId) {\n` +
    `\tconst addrs = ADDRESSES[chainId];\n` +
    `\tif (addrs && Object.keys(addrs).length > 0) return addrs;\n` +
    `\tthrow new Error(\`No deployment found for chain ID \${chainId}\`);\n` +
    `}\n`;

const addressesPath = path.join(__dirname, "../frontend/src/contracts/addresses.js");
fs.writeFileSync(addressesPath, addressesOutput);
console.log("→ frontend/src/contracts/addresses.js");